WebDulich/WebDulich/Controllers/DiadanhController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDulich.Models;
using PagedList;
using PagedList.Mvc;
using System.Xml;
using System.IO;

namespace WebDulich.Controllers
{
    public class DiadanhController : Controller
    {
        DULICHEntities1 data = new DULICHEntities1();
        // GET: Diadanh

        public ActionResult Mienbac(int ?page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 32;
            // return View(data.TINTUCs.ToList());
            return View(data.TINTUCs.ToList().OrderBy(n => n.ID).ToPagedList(pageNumber, pageSize));
        }


        public ActionResult Mientrung(int ?page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 32;
            // return View(data.TINTUCs.ToList());
            return View(data.TINTUCs.ToList().OrderBy(n => n.ID).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Miennam(int ?page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 32;
            // return View(data.TINTUCs.ToList());
            return View(data.TINTUCs.ToList().OrderBy(n => n.ID).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Mientay(int ?page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 32;
            // return View(data.TINTUCs.ToList());
            return View(data.TINTUCs.ToList().OrderBy(n => n.ID).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Taynguyen(int ?page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 32;
            // return View(data.TINTUCs.ToList());
            return View(data.TINTUCs.ToList().OrderBy(n => n.ID).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Biendao(int ?page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 32;
            // return View(data.TINTUCs.ToList());
            return View(data.TINTUCs.ToList().OrderBy(n => n.ID).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Chitiet(int id)
        {
            var tin = from x in data.TINTUCs
                      where x.ID == id
                      select x;
            return View(tin.Single());
        }
    }
}

WebDulich/WebDulich/Views/Diadanh/Biendao.cshtml
@using WebDulich.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<WebDulich.Models.TINTUC>

@{
    ViewBag.Title = "Địa Danh | Biển Đảo";
    Layout = "~/Views/Shared/_LayoutVungmien.cshtml";
}

@section script {
    <!-- Full Page Image Background Carousel Header -->
    <header id="mainCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#mainCarousel" data-slide-to="1"></li>
            <li data-target="#mainCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for Slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="slider_overlay"></div>
                <!-- Set the first background image using inline CSS below. -->
                <div class="fill" style="background-image:url('/Assets/images/taynguyen_1.jpg');">
                </div>
            </div>
            <div class="item">

                <div class="slider_overlay"></div>
                <!-- Set the second background image using inline CSS below. -->
                <div class="fill" style="background-image:url('/Assets/images/taynguyen2.jpg');">
                </div>
            </div>
            <div class="item">
                <div class="slider_overlay"></div>
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" style="background-image:url('/Assets/images/taynguyen3.jpg');">
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#mainCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#mainCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>

    </header>
}

<h2 class="title-search">Du lịch Biển Đảo</h2>
<p>
    <strong>Du lịch Miền Bắc</strong> – Du khách sẽ được trải nghiệm một hành trình văn hóa đậm đà bản sắc cùng khung cảnh thiên nhiên tươi đẹp. <strong>Du lịch Miền Bắc</strong> ghé thăm Hà Nội ngàn năm văn hiến với Hồ Gươm, Tháp Rùa, Văn miếu Quốc Tử Giám ngàn năm tuổi. <strong>Du lịch Miền Bắc</strong> ghé thăm Làng cổ Đường Lâm để đi trên con đường nhỏ lát đá, hai bên đường là những ngôi nhà máu ngói rêu phong. <strong>Du lịch Miền Bắc</strong> không những quyến rũ du khách bằng cảnh đẹp thiên nhiên mà còn thu hút du khách bởi vẫn giữ được những nét văn hóa xưa cũ từ nếp sinh hoạt đến những lễ hội truyền thống còn lưu giữ muôn đời.
</p>

<h2 class="title-search">Danh sách các điểm du lịch</h2>

<div class="col-sm-12 col-md-12">
    @foreach (var item in Model)
    {
        if (item.LOAITIN.TENLOAI == "BIỂN ĐẢO")
        {
            <div id="box-vungmien" class="col-sm-6 col-md-6">
                <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID})">
                    <img src="@item.HINHANH" />
                </a>
                <div id="box-mota">
                    <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID})"><h4><b>@Html.DisplayFor(modelItem => item.TENTIN)</b></h4></a>
                    <h6>@Html.DisplayFor(modelItem => item.MOTA)</h6>
                </div>
                <div class="btn-toolbar text-center">
                    <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID})" role="button" class="button btn btn-success">Xem ngay</a>
                </div>
            </div>
        }
    }
</div>

<div class="col-sm-12 col-md-12 text-center">
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Biendao", new { page = page }))
    </div>
    <style>
        .MenuTrang li {
            display: inline;
        }
    </style>
</div>

WebDulich/WebDulich/Views/Diadanh/Chitiet.cshtml
@model  WebDulich.Models.TINTUC

@{
    ViewBag.Title = "Bài viết";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<!-- Full Page Image Background Carousel Header -->
<header id="mainCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#mainCarousel" data-slide-to="1"></li>
        <li data-target="#mainCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for Slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="slider_overlay"></div>
            <!-- Set the first background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/slide2.jpg');">
            </div>
        </div>
        <div class="item">

            <div class="slider_overlay"></div>
            <!-- Set the second background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/slide1.jpg');">
            </div>
        </div>
        <div class="item">
            <div class="slider_overlay"></div>
            <!-- Set the third background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/slide3.jpg');">
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#mainCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#mainCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>

</header>

<div id="about">
    <div class="container">
        <div id="body">

            <section id="contentt" class="col-xs-12 col-lg-8">
                <h2 class="title_base">
                    <span>&bull;&nbsp;</span>@Model.LOAITIN.TENLOAI<span>&nbsp;&bull;&nbsp;</span>
                </h2>
                @if (Model.ID_USER != null)
            {
                    <p><h4><b>Người viết:</b> @Model.NGUOIDUNG.TENDN</h4></p>
                }
                else if (Model.ID_USERFB != null)
                {
                    <p><h4><b>Người viết:</b> @Model.NGUOIDUNGFB.TENDN</h4></p>
                }
                else
                {
                    <p><h4><b>Người viết: Admin </b></h4></p>
                }
                <div class="col-sm-12 col-md-12 text-left">

                    @Html.Raw(Model.NOIDUNG)

                </div>
                <h2 class="title-search">Ngày đăng: @Model.NGAYDANG</h2>

                <div class="col-sm-12 col-md-12">
                    <div class="fb-comments" data-href="" data-colorscheme="light" data-numposts="5" data-width="100%"></div>
                </div>

                <div id="fb-root"></div>
            </section>

            <section id="contentt" class="col-xs-12 col-lg-4 text-center">
                <h2 class="title-search text-center"> Xem bài viết liên quan </h2>
                @if (Model.LOAITIN.TENLOAI == "MIỀN BẮC")
                {
                    <a href="@Url.Action("Mienbac", "Diadanh")"> <h4>Xem tất cả >></h4></a>
                }
                @if (Model.LOAITIN.TENLOAI == "MIỀN TRUNG")
                {
                    <a href="@Url.Action("Mienbac", "Diadanh")"> <h4>Xem tất cả >></h4></a>
                }
                @if (Model.LOAITIN.TENLOAI == "MIỀN NAM")
                {
                    <a href="@Url.Action("Mienbac", "Diadanh")"> <h4>Xem tất cả >></h4></a>
                }
                @if (Model.LOAITIN.TENLOAI == "MIỀN TÂY")
                {
                    <a href="@Url.Action("Mienbac", "Diadanh")"> <h4>Xem tất cả >></h4></a>
                }
                @if (Model.LOAITIN.TENLOAI == "TÂY NGUYÊN")
                {
                    <a href="@Url.Action("Mienbac", "Diadanh")"> <h4>Xem tất cả >></h4></a>
                }
                @if (Model.LOAITIN.TENLOAI == "BIỂN ĐẢO")
                {
                    <a href="@Url.Action("Mienbac", "Diadanh")"> <h4>Xem tất cả >></h4></a>
                }
                @if (Model.LOAITIN.TENLOAI == "TIN TỨC")
                {
                    <a href="@Url.Action("Mienbac", "Diadanh")"> <h4>Xem tất cả >></h4></a>
                }
                <hr />

                <h2 class="title-search text-center"> Vùng miền </h2>
                <a href="@Url.Action("Mienbac", "Diadanh")"> <h4>Du lịch Miền Bắc</h4></a>
                <hr />
                <a href="@Url.Action("Mientrung", "Diadanh")"> <h4>Du lịch Miền Trung</h4></a>
                <hr />
                <a href="@Url.Action("Miennam", "Diadanh")"> <h4>Du lịch Miền Nam</h4></a>
                <hr />
                <a href="@Url.Action("Mientay", "Diadanh")"> <h4>Du lịch Miền Tây</h4></a>
                <hr />
                <a href="@Url.Action("Taynguyen", "Diadanh")"> <h4>Du lịch Tây Nguyên</h4></a>
                <hr />
                <a href="@Url.Action("Biendao", "Diadanh")"> <h4>Du lịch Biển Đảo</h4></a>
                <hr />
                
                <div class="fb-page" data-href="https://www.facebook.com/kpdulichvn/" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/asstorevn/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/kpdulichvn/">Khám Phá Du Lịch Việt Nam</a></blockquote></div>
            </section>



            @*<aside class="sidebar small-sidebar left-sidebar">

                    <ul>
                        <li>
                            <ul>
                                <li class="text-center">
                                    <span style="color:#fff; font-size:30px; font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif">Vùng Miền</span>
                                    <hr />
                                    <ul>
                                        <li><a href="@Url.Action("Mienbac", "Diadanh")"> <h4>Du lịch Miền Bắc</h4></a></li>
                                        <li><a href="@Url.Action("Mientrung", "Diadanh")"> <h4>Du lịch Miền Trung</h4></a></li>
                                        <li><a href="@Url.Action("Miennam", "Diadanh")"> <h4>Du lịch Miền Nam</h4></a></li>
                                        <li><a href="@Url.Action("Mientay", "Diadanh")"> <h4>Du lịch Miền Tây</h4></a></li>
                                        <li><a href="@Url.Action("Taynguyen", "Diadanh")"> <h4>Du lịch Tây Nguyên</h4></a></li>
                                        <li><a href="@Url.Action("Biendao", "Diadanh")"> <h4>Du lịch Biển Đảo</h4></a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <div class="fb-page" data-href="https://www.facebook.com/kpdulichvn/" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/asstorevn/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/asstorevn/">As Shop - Quần áo thể thao Nike, Adidas</a></blockquote></div>

                </aside>*@



        </div>
    </div>
</div>

WebDulich/WebDulich/Views/Diadanh/Mienbac.cshtml
@using WebDulich.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<WebDulich.Models.TINTUC>

@{
    ViewBag.Title = "Địa Danh | Miền Bắc";
    Layout = "~/Views/Shared/_LayoutVungmien.cshtml";
}

@section script {
    <!-- Full Page Image Background Carousel Header -->
<header id="mainCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#mainCarousel" data-slide-to="1"></li>
        <li data-target="#mainCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for Slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="slider_overlay"></div>
            <!-- Set the first background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/mienbac_sl1.jpg');">
            </div>
        </div>
        <div class="item">

            <div class="slider_overlay"></div>
            <!-- Set the second background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/mienbac_sl2.jpg');">
            </div>
        </div>
        <div class="item">
            <div class="slider_overlay"></div>
            <!-- Set the third background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/mienbac_sl3.jpg');">
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#mainCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#mainCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>

</header>
}

<h2 class="title_base">Du lịch Miền Bắc</h2>
<p>
    <strong>Du lịch Miền Bắc</strong> – Du khách sẽ được trải nghiệm một hành trình văn hóa đậm đà bản sắc cùng khung cảnh thiên nhiên tươi đẹp. <strong>Du lịch Miền Bắc</strong> ghé thăm Hà Nội ngàn năm văn hiến với Hồ Gươm, Tháp Rùa, Văn miếu Quốc Tử Giám ngàn năm tuổi. <strong>Du lịch Miền Bắc</strong> ghé thăm Làng cổ Đường Lâm để đi trên con đường nhỏ lát đá, hai bên đường là những ngôi nhà máu ngói rêu phong. <strong>Du lịch Miền Bắc</strong> không những quyến rũ du khách bằng cảnh đẹp thiên nhiên mà còn thu hút du khách bởi vẫn giữ được những nét văn hóa xưa cũ từ nếp sinh hoạt đến những lễ hội truyền thống còn lưu giữ muôn đời.
</p>

<h2 class="title_base">Danh sách các điểm du lịch</h2>


<div class="col-sm-12 col-md-12">
    @foreach (var item in Model)
    {
        if (item.LOAITIN.TENLOAI == "MIỀN BẮC")
        {
            <div id="box-vungmien" class="col-sm-6 col-md-6">
                <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID})">
                    <img src="@item.HINHANH" />
                </a>
                <div id="box-mota">
                    <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID })"><h4><b>@Html.DisplayFor(modelItem => item.TENTIN)</b></h4></a>
                    <h6>@Html.DisplayFor(modelItem => item.MOTA)</h6>
                </div>
                <div class="btn-toolbar text-center">
                    <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID})" role="button" class="button btn btn-success">Xem ngay</a>
                </div>
            </div>
        }
    }
</div>

<div class="col-sm-12 col-md-12 text-center">
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Mienbac", new { page = page }))
    </div>
    <style>
        .MenuTrang li {
            display: inline;
        }
    </style>

</div>

WebDulich/WebDulich/Views/Diadanh/Miennam.cshtml
@using WebDulich.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<WebDulich.Models.TINTUC>
@{
    ViewBag.Title = "Địa Danh | Miền Nam";
    Layout = "~/Views/Shared/_LayoutVungmien.cshtml";
}
@section script {
    <!-- Full Page Image Background Carousel Header -->
    <header id="mainCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#mainCarousel" data-slide-to="1"></li>
            <li data-target="#mainCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for Slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="slider_overlay"></div>
                <!-- Set the first background image using inline CSS below. -->
                <div class="fill" style="background-image:url('/Assets/images/miennam_3.jpg');">
                </div>
            </div>
            <div class="item">

                <div class="slider_overlay"></div>
                <!-- Set the second background image using inline CSS below. -->
                <div class="fill" style="background-image:url('/Assets/images/miennam_1.jpg');">
                </div>
            </div>
            <div class="item">
                <div class="slider_overlay"></div>
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" style="background-image:url('/Assets/images/miennam_2.jpg');">
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#mainCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#mainCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>

    </header>
}

<h2 class="title-search">Du lịch Miền Nam</h2>
<p>
    <strong>Du lịch Miền Nam</strong> nổi tiếng với những cánh đồng lúa thẳng cánh cò bay cùng hệ thống sông ngòi chằng chịt.<strong> Du lịch Miền Nam </strong>với những chiến tích vang dội còn lưu danh nơi căn cứ Minh Đạm, TW Cục miền Nam hay Côn Đảo, Phú Quốc. Đến với <strong>Du lịch Miền Nam</strong> không thể không nhắc đến một Thành phố Hồ Chí Minh sôi động, náo nhiệt sẽ mang đến cho du khách những ngày nghỉ thật tưng bừng.
</p>

<h2 class="title-search">Danh sách các điểm du lịch</h2>

<div class="col-sm-12 col-md-12">
    @foreach (var item in Model)
    {
        if (item.LOAITIN.TENLOAI == "MIỀN NAM")
        {
            <div id="box-vungmien" class="col-sm-6 col-md-6 column-space">
                <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID})">
                    <img src="@item.HINHANH" />
                </a>
                <div id="box-mota">
                    <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID})"><h4><b>@Html.DisplayFor(modelItem => item.TENTIN)</b></h4></a>
                    <h6>@Html.DisplayFor(modelItem => item.MOTA)</h6>
                </div>
                <div class="btn-toolbar text-center">
                    <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID})" role="button" class="button btn btn-success">Xem ngay</a>
                </div>
            </div>
        }
    }
</div>

<div class="col-sm-12 col-md-12 text-center">
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Miennam", new { page = page }))
    </div>
    <style>
        .MenuTrang li {
            display: inline;
        }
    </style>
</div>

WebDulich/WebDulich/Views/Diadanh/Mientay.cshtml
@using WebDulich.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<WebDulich.Models.TINTUC>

@{
    ViewBag.Title = "Địa Danh | Miền Tây";
    Layout = "~/Views/Shared/_LayoutVungmien.cshtml";
}
@section script {
    <!-- Full Page Image Background Carousel Header -->
    <header id="mainCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#mainCarousel" data-slide-to="1"></li>
            <li data-target="#mainCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for Slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="slider_overlay"></div>
                <!-- Set the first background image using inline CSS below. -->
                <div class="fill" style="background-image:url('/Assets/images/mientay_1.jpg');">
                </div>
            </div>
            <div class="item">

                <div class="slider_overlay"></div>
                <!-- Set the second background image using inline CSS below. -->
                <div class="fill" style="background-image:url('/Assets/images/mientay_2.jpg');">
                </div>
            </div>
            <div class="item">
                <div class="slider_overlay"></div>
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" style="background-image:url('/Assets/images/mientay_3.jpg');">
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#mainCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#mainCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>

    </header>
}

<h2 class="title-search">Du lịch Miền Tây</h2>
<p>
    <strong>Du lịch Miền Bắc</strong> – Du khách sẽ được trải nghiệm một hành trình văn hóa đậm đà bản sắc cùng khung cảnh thiên nhiên tươi đẹp. <strong>Du lịch Miền Bắc</strong> ghé thăm Hà Nội ngàn năm văn hiến với Hồ Gươm, Tháp Rùa, Văn miếu Quốc Tử Giám ngàn năm tuổi. <strong>Du lịch Miền Bắc</strong> ghé thăm Làng cổ Đường Lâm để đi trên con đường nhỏ lát đá, hai bên đường là những ngôi nhà máu ngói rêu phong. <strong>Du lịch Miền Bắc</strong> không những quyến rũ du khách bằng cảnh đẹp thiên nhiên mà còn thu hút du khách bởi vẫn giữ được những nét văn hóa xưa cũ từ nếp sinh hoạt đến những lễ hội truyền thống còn lưu giữ muôn đời.
</p>

<h2 class="title-search">Danh sách các điểm du lịch</h2>

<div class="col-sm-12 col-md-12">
    @foreach (var item in Model)
    {
        if (item.LOAITIN.TENLOAI == "MIỀN TÂY")
        {
            <div id="box-vungmien" class="col-sm-6 col-md-6 column-space">
                <a href="@Url.Action("Chitiet","Diadanh", new {id = item.ID})">
                    <img src="@item.HINHANH" />
                </a>
                <div id="box-mota">
                    <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID})"><h4><b>@Html.DisplayFor(modelItem => item.TENTIN)</b></h4></a>
                    <h6>@Html.DisplayFor(modelItem => item.MOTA)</h6>
                </div>
                <div class="btn-toolbar text-center">
                    <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID})" role="button" class="button btn btn-success">Xem ngay</a>
                </div>
            </div>
        }
    }
</div>

<div class="col-sm-12 col-md-12 text-center">
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Mientay", new { page = page }))
    </div>
    <style>
        .MenuTrang li {
            display: inline;
        }
    </style>



</div>