WebDulich/WebDulich/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDulich.Models;
using System.Web.Security;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Configuration;
using Facebook;
using System.Security.Cryptography;
using System.Text;
using System.Data.Entity;
using System.Globalization;
using System.Text.RegularExpressions;
using System.Net.Mail;
using System.Net;

namespace WebDulich.Controllers
{


    public class UserAccountController : Controller
    {
        bool invalid = false;

        public static string CreateLostPassword(int PasswordLength)
        {
            string _allowedChars = "abcdefghijk0123456789mnopqrstuvwxyz";
            Random randNum = new Random();
            char[] chars = new char[PasswordLength];
            int allowedCharCount = _allowedChars.Length;

            for (int i = 0; i < PasswordLength; i++)
            {
                chars[i] = _allowedChars[(int)((_allowedChars.Length) * randNum.NextDouble())];
            }
            return new string(chars);
        }

        public bool IsValidEmail(string strIn)
        {
            
            invalid = false;
            if (String.IsNullOrEmpty(strIn))
                return false;

            // Use IdnMapping class to convert Unicode domain names.
            try
            {
                strIn = Regex.Replace(strIn, @"(@)(.+)$", this.DomainMapper,
                                      RegexOptions.None, TimeSpan.FromMilliseconds(200));
            }
            catch (RegexMatchTimeoutException)
            {
                return false;
            }

            if (invalid)
                return false;

            // Return true if strIn is in valid e-mail format.
            try
            {
                return Regex.IsMatch(strIn,
                      @"^(?("")("".+?(?<!\\)""@)|(([0-9a-z]((\.(?!\.))|[-!#\$%&'\*\+/=\?\^`\{\}\|~\w])*)(?<=[0-9a-z])@))" +
                      @"(?(\[)(\[(\d{1,3}\.){3}\d{1,3}\])|(([0-9a-z][-\w]*[0-9a-z]*\.)+[a-z0-9][\-a-z0-9]{0,22}[a-z0-9]))$",
                      RegexOptions.IgnoreCase, TimeSpan.FromMilliseconds(250));
            }
            catch (RegexMatchTimeoutException)
            {
                return false;
            }
        }

        private string DomainMapper(Match match)
        {
            // IdnMapping class with default property values.
            IdnMapping idn = new IdnMapping();

            string domainName = match.Groups[2].Value;
            try
            {
                domainName = idn.GetAscii(domainName);
            }
            catch (ArgumentException)
            {
                invalid = true;
            }
            return match.Groups[1].Value + domainName;
        }

        public static string MD5Hash(string text)
        {
            MD5 md5 = new MD5CryptoServiceProvider();


            md5.ComputeHash(ASCIIEncoding.ASCII.GetBytes(text));


            byte[] result = md5.Hash;

            StringBuilder strBuilder = new StringBuilder();
            for (int i = 0; i < result.Length; i++)
            {

                strBuilder.Append(result[i].ToString("x2"));
            }

            return strBuilder.ToString();
        }

        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallBack");
                return uriBuilder.Uri;
            }
        }
        DULICHEntities1 data = new DULICHEntities1();
        
        

        public object FormAuthentication { get; private set; }

        // GET: UserAccount
        public ActionResult Dangky()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangky(FormCollection collection, NGUOIDUNG us)
        {
            THONGKEWEB data_tk = data.THONGKEWEBs.SingleOrDefault(n => n.ID ==1);
            var tendn = collection["TENDN"];
            var email = collection["EMAIL"];
            var matkhau = collection["PASS"];
            var matkhaunhaplai = collection["PASS2"];
            var ten = collection["TEN"];
            var sodt = collection["SODT"];
            foreach (var item in data.NGUOIDUNGs)
            {
                if (tendn == item.TENDN)
                {
                    ViewData["Loi1-1"] = "Tên đăng nhập này đã có người sử dụng";
                    return this.Dangky();
                }
                else if (email == item.EMAIL)
                {
                    ViewData["Loi1-2"] = "Email này đã có người sử dụng";
                    return this.Dangky();
                }

            }
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Tên đăng nhập không được để trống";
            }

            else if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi2"] = "Email không được để trống";
            }

            else if (!IsValidEmail(email))
            {
                ViewData["Loi2-2"] = "Email không đúng định dạng";
            }

            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Phải nhập mật khẩu";
            }
            else if (matkhau != matkhaunhaplai)
            {
                ViewData["Loi4"] = "Mật khẩu nhập lại không đúng";
            }
            else if (String.IsNullOrEmpty(ten))
            {
                ViewData["Loi5"] = "Phải nhập họ tên";
            }
            else if (String.IsNullOrEmpty(sodt))
            {
                ViewData["Loi6"] = "Phải nhập số điện thoại";
            }
            else
            {
                matkhau = MD5Hash(matkhau);
                us.TENDN = tendn;
                us.EMAIL = email;
                us.PASS = matkhau;
                us.TEN = ten;
                us.SODT = sodt;
                data.NGUOIDUNGs.Add(us);
                data_tk.TOTAL_USER++;
                data.SaveChanges();
               
                return RedirectToAction("Dangnhap");
            }
            return this.Dangky();
        }

        public ActionResult Dangnhap()
        {
            NGUOIDUNG nd = (NGUOIDUNG)Session["Taikhoan"];
            ADMIN ad = (ADMIN)Session["Admin"];
            NGUOIDUNGFB ndfb = (NGUOIDUNGFB)Session["TaikhoanFB"];
            if (nd != null || ndfb != null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (ad != null)
            {
                return RedirectToAction("Index", "AdminManager");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Dangnhap(FormCollection collection)
        {
            THONGKEWEB data_tk = data.THONGKEWEBs.SingleOrDefault(n => n.ID ==1);
            var tendn = collection["TENDN"];
            var matkhau = collection["PASS"];
            matkhau = MD5Hash(matkhau);
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu";
            }
            else
            {
                NGUOIDUNG nd = data.NGUOIDUNGs.SingleOrDefault(n => n.TENDN == tendn && n.PASS == matkhau);
                ADMIN ad = data.ADMINs.SingleOrDefault(n => n.USERNAME == tendn && n.PASSWORD == matkhau);

                if (ad != null)
                {
                    Session["Admin"] = ad;
                    return RedirectToAction("Index", "Home");
                }
                if (nd != null)
                {
                    Session["TaiKhoan"] = nd;
                    data_tk.TOTAL_ONL++;
                    data.SaveChanges();
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }

            }
            return this.Dangnhap();
        }



        public ActionResult LogInFaceBook()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = ConfigurationManager.AppSettings["FBAppId"],
                client_secret = ConfigurationManager.AppSettings["FBAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                reponse_type = "code",
                scope = "email",
            });
            return Redirect(loginUrl.AbsoluteUri);
        }

        public ActionResult FacebookCallBack(string code)
        {
            var fb = new FacebookClient();
            THONGKEWEB data_tk = data.THONGKEWEBs.SingleOrDefault(n => n.ID == 1);
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = ConfigurationManager.AppSettings["FBAppId"],
                client_secret = ConfigurationManager.AppSettings["FBAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });
            var accessToken = result.access_token;
            if (!string.IsNullOrEmpty(accessToken))
            {
                fb.AccessToken = accessToken;
                dynamic me = fb.Get("me?fields=first_name,middle_name,last_name,id,email");
                string email = me.email;
                string id = me.id;
                string firstName = me.first_name;
                string middleName = me.middle_name;
                string lastName = me.last_name;
                NGUOIDUNGFB check_us = data.NGUOIDUNGFBs.SingleOrDefault(n => n.ID == id);
                if (check_us == null)
                {
                    NGUOIDUNGFB us = new NGUOIDUNGFB();

WebDulich/WebDulich/Views/UserAccount/Chinhsach.cshtml
@{
    ViewBag.Title = "Chinhsach";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<header id="mainCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#mainCarousel" data-slide-to="1"></li>
        <li data-target="#mainCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for Slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="slider_overlay"></div>
            <!-- Set the first background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/slide2.jpg');">
            </div>
        </div>
        <div class="item">

            <div class="slider_overlay"></div>
            <!-- Set the second background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/slide1.jpg');">
            </div>
        </div>
        <div class="item">
            <div class="slider_overlay"></div>
            <!-- Set the third background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/slide3.jpg');">
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#mainCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#mainCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>

</header>

<div id="about">
    <div class="main-content">

    </div>
</div>

WebDulich/WebDulich/Views/UserAccount/Dangky.cshtml
@model WebDulich.Models.TINTUC

@{
    ViewBag.Title = "Khám Phá | Đăng Ký";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container">
    <!-- main -->
    <div class="main">

        <div class="login-form">
            <h2>Đăng Ký</h2>
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
                <div class="agileits-top">
                    <div class="styled-input">

                        <font color="red">
                            @ViewData["Loi1"]
                            @ViewData["Loi1-1"]
                        </font>
                        <input type="text" name="TENDN" />
                        <label>Tên đăng nhập</label>
                        <span></span>
                    </div>
                    <div class="styled-input">

                        <font color="red">
                            @ViewData["Loi2"]
                            @ViewData["Loi1-2"]
                            @ViewData["Loi2-2"]
                        </font>
                        <input type="text" name="EMAIL"/>
                        <label>Email</label>
                        <span></span>
                    </div>
                    <div class="styled-input">

                        <font color="red">
                            @ViewData["Loi3"]
                        </font>
                        <input type="password" name="PASS" />
                        <label>Mật khẩu</label>
                        <span></span>
                    </div>
                    <div class="styled-input">

                        <font color="red">
                            @ViewData["Loi4"]
                        </font>
                        <input type="password" name="PASS2" />
                        <label>Nhập lại mật khẩu</label>
                        <span></span>
                    </div>
                    <div class="styled-input">

                        <font color="red">
                            @ViewData["Loi5"]
                        </font>
                        <input type="text" name="TEN"/>
                        <label>Họ tên</label>
                        <span></span>
                    </div>
                    <div class="styled-input">

                        <font color="red">
                            @ViewData["Loi6"]
                        </font>
                        <input type="text" name="SODT" pattern="[0-9]{9,11}"/>
                        <label>Điện thoại</label>
                        <span></span>
                    </div>
                    <div class="clear"> </div>
                </div>
                <div class="agileits-bottom">
                    <input type="submit" value="Đăng Ký">
                </div>
            }

        </div>
    </div>
    <!-- //main -->
</div>

WebDulich/WebDulich/Views/UserAccount/Dangnhap.cshtml
@model  WebDulich.Models.TINTUC

@{
    ViewBag.Title = "Khám Phá | Đăng Nhập";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container">
    <!-- main -->
    <div class="main">
        <h4 style="color:red; text-align:center">@ViewBag.Thongbao</h4>
        <div class="login-form">
            <h2>Đăng Nhập</h2>
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
                <div class="agileits-top">
                    <div class="styled-input">
                        <font color="red">
                            @ViewData["Loi1"]
                        </font>
                        @Html.TextBox("TENDN")
                        <label>Tên đăng nhập</label>
                        <span></span>
                    </div>
                    <div class="styled-input">
                        <font color="red">
                            @ViewData["Loi2"]
                        </font>
                        @Html.Password("PASS")
                        <label>Mật khẩu</label>
                        <span></span>
                    </div>
                    <div class="wthree-text">
                        <ul>
                            <li> <a href="@Url.Action("Quenmatkhau","UserAccount")">Quên mật khẩu?</a> </li>
                        </ul>
                        <div class="clear"> </div>
                    </div>
                </div>
                <div class="agileits-bottom">
                    <input type="submit" value="Đăng Nhập">
                </div>
            }
            <br />
            <div>
                <ul>
                    <li class="text">
                        <p style="margin: 0;">Nếu bạn chưa có tài khoản, hãy đăng ký tài khoản bằng đường dẫn bên dưới.</p>
                    </li>
                </ul>
                <a type="button" class="btn btn-success" href="@Url.Action("Dangky","UserAccount")">Tạo tài khoản</a>
            </div>
            <br />
            <a class="btn btn-facebook" href="/UserAccount/LogInFacebook">
                <i class="fa fa-facebook"></i>
                Đăng Nhập Bằng FaceBook
            </a>
            <br />
            <br />
            <a class="btn btn-google" href="/UserAccount/LogInFacebook">
                <i class="fa fa-google-plus"></i>
                Đăng Nhập Bằng Gmail
            </a>
        </div>
    </div>
    <!-- //main -->
</div>

WebDulich/WebDulich/Views/UserAccount/Doimatkhau.cshtml
@model WebDulich.Models.TINTUC

@{
    ViewBag.Title = "Khám Phá | Đổi Mật Khẩu";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container">
    <!-- main -->
    <div class="main">

        <div class="login-form">
            <h2>Đổi Mật Khẩu</h2>
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
                <div class="agileits-top">

                    <div class="styled-input">
                        <font color="red">
                            @ViewData["Loi1"]
                        </font>
                        <input type="password" name="OldPass" />
                        <label>Mật khẩu cũ</label>
                        <span></span>
                    </div>

                    <div class="styled-input">
                        <font color="red">
                            @ViewData["Loi2"]
                        </font>
                        <input type="password" name="NewPass" />
                        <label>Mật khẩu mới</label>
                        <span></span>
                    </div>

                    <div class="styled-input">
                        <font color="red">
                            @ViewData["Loi3"]
                        </font>
                        <input type="password" name="ConfirmPass" />
                        <label>Xác nhận mật khẩu</label>
                        <span></span>
                    </div>


                    <div class="clear"> </div>
                </div>
                <div class="agileits-bottom">
                    <input type="submit" value="Đồng Ý">
                </div>
            }

        </div>
    </div>
    <!-- //main -->
</div>

WebDulich/WebDulich/Views/UserAccount/Quenmatkhau.cshtml
@{
    ViewBag.Title = "Lấy Lại Mật Khẩu";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="container">
    <!-- main -->
    <div class="main">

        <div class="login-form">
            <h2>Lấy Lại Mật Khẩu</h2>
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
                <div class="agileits-top">

                    <div class="styled-input">
                        <font color="red">
                            @ViewData["Loi1"]
                            @ViewData["Loi2"]
                            @ViewData["Loi3"]
                        </font>
                        <input type="text" name="Email" />
                        <label>Mời nhập email:</label>

                        <span></span>
                    </div>

                    <div class="clear"> </div>
                </div>
                <div class="agileits-bottom">
                    <input type="submit" value="Đồng Ý" href="@Url.Action("Dangnhap","UserAccout")">
                </div>
            }

        </div>
    </div>
    <!-- //main -->
</div>

WebDulich/WebDulich/Views/UserAccount/Thongtin.cshtml
@using WebDulich.Models;

@{ 
    NGUOIDUNG nd = (NGUOIDUNG)Session["TaiKhoan"];
    NGUOIDUNGFB ndfb = (NGUOIDUNGFB)Session["TaiKhoanFB"];
   
}

@{
    ViewBag.Title = "Khám Phá | Thông Tin";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<header id="mainCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#mainCarousel" data-slide-to="1"></li>
        <li data-target="#mainCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for Slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="slider_overlay"></div>
            <!-- Set the first background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/slide2.jpg');">
            </div>
        </div>
        <div class="item">

            <div class="slider_overlay"></div>
            <!-- Set the second background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/slide1.jpg');">
            </div>
        </div>
        <div class="item">
            <div class="slider_overlay"></div>
            <!-- Set the third background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/slide3.jpg');">
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#mainCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#mainCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>

</header>

<div id="about">
    <div class="container">
        <div class="col-md-12">
            @if (nd != null)
            {
                <h2 class="title_base text-center">Thông tin người dùng</h2>
                <div class="display-label"><b>Tên người dùng: @nd.TEN</b></div>
                <div class="display-label"><b>Email: @nd.EMAIL</b></div>
                <div class="display-label"><b>Tên đăng nhập: @nd.TENDN</b></div>
                <div class="display-label"><b>Mật khẩu: &bullet;&bullet;&bullet;&bullet;&bullet;&bullet;&bullet;&bullet;&bullet;&bullet;</b></div>
                <div class="display-label"><b>Số điện thoại: @nd.SODT</b></div>
                <br />
                <h2 class="title_base text-left">Bài viết đã đăng</h2>
                foreach (var item in nd.TINTUCs)
                {
                    <div class="col-md-4">
                        <small>@item.NGAYDANG</small>
                        <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID})">
                            <img src="@item.HINHANH" />
                        </a>
                        <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID })"><h4><b>@Html.DisplayFor(modelItem => item.TENTIN)</b></h4></a>
                    </div>
                }
                <h2 class="title_base text-left">Bài viết đang chờ duyệt</h2>
                foreach (var item in nd.BAIVIETs)
                {
                    <div class="col-md-4">
                        <h4><b>@Html.DisplayFor(modelItem => item.TIEUDE)</b></h4>
                        <small>@item.NGAYDANG</small>
                        <img src="@item.ANHBIA" />
                    </div>
                }
            }
            else if (ndfb != null)
            {
                <h2 class="title_base text-center">Thông tin người dùng</h2>
                <div class="display-label"><b>Tên người dùng: @ndfb.TEN</b></div>
                <div class="display-label"><b>Email: @ndfb.EMAIL</b></div>
                <div class="display-label"><b>Tên đăng nhập: @ndfb.TENDN</b></div>
                <br />
                <h2 class="title_base text-left">Bài viết đã đăng</h2>
                foreach (var item in ndfb.TINTUCs)
                {
                    <div class="col-md-4">
                        <small>@item.NGAYDANG</small>
                        <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID})">
                            <img src="@item.HINHANH" />
                        </a>
                        <a href="@Url.Action("Chitiet","Diadanh", new { id = item.ID })"><h4><b>@Html.DisplayFor(modelItem => item.TENTIN)</b></h4></a>
                    </div>
                }
                <h2 class="title_base text-left">Bài viết đang chờ duyệt</h2>
                foreach (var item in nd.BAIVIETs)
                {
                    <div class="col-md-4">
                        <h4><b>@Html.DisplayFor(modelItem => item.TIEUDE)</b></h4>
                        <small>@item.NGAYDANG</small>
                        <img src="@item.ANHBIA" />
                    </div>
                }
            }

            <br />
        </div>
        
    </div>
</div>

WebDulich/WebDulich/Views/UserAccount/Vietbai.cshtml
@model WebDulich.Models.BAIVIET
@using WebDulich.Models;

@{
    NGUOIDUNG nd = (NGUOIDUNG)Session["TaiKhoan"];
    NGUOIDUNGFB ndfb = (NGUOIDUNGFB)Session["TaiKhoanFB"];
}

@{
    ViewBag.Title = "Khám Phá | Viết Bài";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<header id="mainCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#mainCarousel" data-slide-to="1"></li>
        <li data-target="#mainCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for Slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="slider_overlay"></div>
            <!-- Set the first background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/slide2.jpg');">
            </div>
        </div>
        <div class="item">

            <div class="slider_overlay"></div>
            <!-- Set the second background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/slide1.jpg');">
            </div>
        </div>
        <div class="item">
            <div class="slider_overlay"></div>
            <!-- Set the third background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/Assets/images/slide3.jpg');">
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#mainCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#mainCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>

</header>

<div id="about">
    <div class="container">
        <h2 class="title_base text-center">Viết Bài</h2>
        <label class="control-label col-sm-12 col-md-12 text-left" style="color:red"><i>Để viết bài vui lòng đọc kỹ nội dung hướng dẫn viết bài </i><a href="@Url.Action("Noiquy", "UserAccount")">tại đây</a></label>       
        <br />
        <br />
        @using (Html.BeginForm("Vietbai", "UserAccount", null, FormMethod.Post, new { enctype = "multipart/form-data", id = "formCreate" }))
        {
            @Html.AntiForgeryToken()
            <label class="control-label col-sm-12 col-md-12 text-center" style="color:red">@ViewBag.Thongbao</label>
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <label class="control-label col-md-3" for="pwd">Loại tin:</label>
                    <div class="col-md-5">
                        @Html.DropDownListFor(model => model.ID_LOAI, ViewBag.listCate as IEnumerable<SelectListItem>, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3" for="pwd">Tiêu đề:</label>
                    <div class="col-md-5" >
                        @Html.EditorFor(model => model.TIEUDE, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TIEUDE, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3" for="pwd">Mô tả:</label>
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.MOTA, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MOTA, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3" for="pwd">Hình ảnh:</label>
                    <div class="col-md-5">
                        <input type="file" name="hinh" class="form-control" />
                    </div>
                </div>

                @*<div class="form-group">
                    <label class="control-label col-md-3" for="pwd">Ngày đăng:</label>
                    <div class="col-md-5">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            @Html.EditorFor(model => model.NGAYDANG, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NGAYDANG, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>*@

                <div class="form-group">
                    <label class="control-label col-sm-3" for="pwd">Nội dung:</label>
                    <div class="col-sm-7">
                        <textarea id="editor2" name="noidung" rows="3">
                            
                        </textarea>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-3 col-md-7    ">
                       <label>
                           <input type="checkbox" name="r1" class="minimal">
                           Tôi đảm bảo rằng những đánh giá trên là trải nghiệm chân thực và cảm nhận khách quan của riêng tôi về địa điểm này. Tôi hiểu rằng Dulichvietnam.com có quy định nghiêm ngặt về những đánh giá không chân thật <a href="@Url.Action("Noiquy", "UserAccount")">Tìm hiểu thêm</a>
                       </label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-6 col-md-10">
                        <input type="submit" value="Đăng bài" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>