WebDulich/WebDulich/Controllers/AdminManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDulich.Models;
using System.IO;
using System.Data.Entity.Infrastructure;
using System.Data.Entity;
using PagedList;
using PagedList.Mvc;
using System.Text;
using System.Text.RegularExpressions;
using WebDulich.App_Start;


namespace WebDulich.Areas.Admin.Controllers
{

    public class AdminManagerController : Controller
    {
        DULICHEntities1 data = new DULICHEntities1();
        
        // GET: Admin
       
        public ActionResult Index()
        {
            
            ADMIN ad = (ADMIN)Session["Admin"];
            if(ad == null)
            {
                return RedirectToAction("Index", "Home");
            }
            THONGKEWEB tk_web = data.THONGKEWEBs.SingleOrDefault(n => n.ID == 1);
            
            ViewBag.USER = tk_web.TOTAL_USER;
            ViewBag.BAIVIET = tk_web.TOTAL_BAIVIET;
            ViewBag.ONL = tk_web.TOTAL_ONL;
            ViewBag.TINTUC = tk_web.TOTAL_TINTUC;
            return View();
        }

        public ActionResult ListPost(int? page)
        {
            ADMIN ad = (ADMIN)Session["Admin"];
            if (ad == null)
            {
                return RedirectToAction("Index", "Home");
            }
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            // return View(data.TINTUCs.ToList());
            return View(data.TINTUCs.ToList().OrderBy(n => n.ID).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult SearchPost(string sTuKhoa, int? page)
        {
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }
            int Pagesize = 9;
            int PageNumber = (page ?? 1);

            string TuKhoa = sTuKhoa;
            TuKhoa = TuKhoa.GenerateSlug();

            var tin = data.TINTUCs.Where(n => n.TUKHOA.Contains(TuKhoa));
            ViewBag.TuKhoa = sTuKhoa;
            return View(tin.OrderBy(n => n.TENTIN).ToPagedList(PageNumber, Pagesize));

        }
        [HttpPost]
        public ActionResult SearchPost(string sTuKhoa)
        {
            return RedirectToAction("SearchPost", new { @sTuKhoa = sTuKhoa });

        }

        public ActionResult CreatePost()
        {
            ADMIN ad = (ADMIN)Session["Admin"];
            if (ad == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var listCategory = from s in data.LOAITINs
                               select new { s.ID, s.TENLOAI };

            var list = listCategory.ToList().Select(c => new SelectListItem
            {
                Text = c.TENLOAI,
                Value = c.ID.ToString(),
                Selected = (c.ID == 1)
            }).ToList();

            ViewBag.listCate = list;
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreatePost([Bind(Include = "TENTIN, MOTA, NGAYDANG, ID_LOAI")] TINTUC tin, FormCollection collection)
        {
            THONGKEWEB tk_web = data.THONGKEWEBs.SingleOrDefault(n => n.ID == 1);
            var noidung = collection["noidung"];
            var hinh = collection["hinh"];
            
            try
            {
                if (ModelState.IsValid)
                {
                    tin.TUKHOA = tin.TENTIN;
                    tin.TUKHOA = tin.TUKHOA.GenerateSlug();
                    tin.NGAYDANG = DateTime.Now;
                    tin.HINHANH = hinh;
                    tin.NOIDUNG = noidung;
                    data.TINTUCs.Add(tin);
                    tk_web.TOTAL_TINTUC++;
                    data.SaveChanges();
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Có lỗi xảy ra");
            }
            return RedirectToAction("ListPost");
        }

        public ActionResult DetailPost(int id)
        {
            ADMIN ad = (ADMIN)Session["Admin"];
            if (ad == null)
            {
                return RedirectToAction("Index", "Home");
            }
            TINTUC tin = data.TINTUCs.SingleOrDefault(n => n.ID == id);
            ViewBag.Matin = tin.ID;
            if (tin == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(tin);
        }

        public ActionResult DeletePost(int id)
        {
            ADMIN ad = (ADMIN)Session["Admin"];
            if (ad == null)
            {
                return RedirectToAction("Index", "Home");
            }
            TINTUC tin = data.TINTUCs.SingleOrDefault(n => n.ID == id);
            ViewBag.Matin = tin.ID;
            if (tin == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(tin);
        }

        [HttpPost, ActionName("DeletePost")]
        public ActionResult DeletePost(int id, FormCollection collection)
        {
            THONGKEWEB tk_web = data.THONGKEWEBs.SingleOrDefault(n => n.ID == 1);
            TINTUC tin = data.TINTUCs.SingleOrDefault(n => n.ID == id);
            ViewBag.Matin = tin.ID;
            if (tin == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            data.TINTUCs.Remove(tin);
            tk_web.TOTAL_TINTUC--;
            data.SaveChanges();
            return RedirectToAction("ListPost");
        }

        public ActionResult EditPost(int id)
        {
            ADMIN ad = (ADMIN)Session["Admin"];
            if (ad == null)
            {
                return RedirectToAction("Index", "Home");
            }
            TINTUC tin = data.TINTUCs.SingleOrDefault(n => n.ID == id);
            ViewBag.Matin = tin.ID;
            if (tin == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            var listCategory = from s in data.LOAITINs
                               select new { s.ID, s.TENLOAI };

            var list = listCategory.ToList().Select(c => new SelectListItem
            {
                Text = c.TENLOAI,
                Value = c.ID.ToString(),
                Selected = (c.ID == 1)
            }).ToList();

            ViewBag.listCate = list;
            return View(tin);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditPost(int id, FormCollection collection)
        {
            TINTUC tin = data.TINTUCs.SingleOrDefault(n => n.ID == id);
            var noidung = collection["noidung"];
            var hinh = collection["hinh"];
            var tentin = collection["TENTIN"];
            var mota = collection["MOTA"];
            var loaitin = int.Parse(collection["ID_LOAI"]);
            try
            {
                if (ModelState.IsValid)
                {
                    tin.ID_LOAI = loaitin;
                    tin.TENTIN = tentin;
                    tin.TUKHOA = tin.TENTIN;
                    tin.TUKHOA = tin.TUKHOA.GenerateSlug();
                    tin.MOTA = mota;
                    tin.HINHANH = hinh;
                    tin.NOIDUNG = noidung;
                    data.Entry(tin).State = EntityState.Modified;
                    data.SaveChanges();
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Có lỗi xảy ra");
            }
            return RedirectToAction("ListPost");
        }

        // Quản lý người dùng
        public ActionResult ListUser(int? page)
        {
            ADMIN ad = (ADMIN)Session["Admin"];
            if (ad == null)
            {
                return RedirectToAction("Index", "Home");
            }
            int pageNumber = (page ?? 1);
            int pageSize = 7;
            // return View(data.TINTUCs.ToList());
            return View(data.NGUOIDUNGs.ToList().OrderBy(n => n.ID).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult SearchUser(string sTuKhoa, int? page)
        {
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }
            int Pagesize = 9;
            int PageNumber = (page ?? 1);

            var us = data.NGUOIDUNGs.Where(n => n.TENDN.Contains(sTuKhoa));
            ViewBag.TuKhoa = sTuKhoa;
            return View(us.OrderBy(n => n.TENDN).ToPagedList(PageNumber, Pagesize));

        }
        [HttpPost]
        public ActionResult SearchUser(string sTuKhoa)
        {
            return RedirectToAction("SearchUser", new { @sTuKhoa = sTuKhoa });

        }

        public ActionResult DetailUser(int id)
        {
            ADMIN ad = (ADMIN)Session["Admin"];
            if (ad == null)
            {
                return RedirectToAction("Index", "Home");
            }
            NGUOIDUNG nd = data.NGUOIDUNGs.SingleOrDefault(n => n.ID == id);
            ViewBag.Mand = nd.ID;
            if (nd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(nd);
        }

        public ActionResult DeleteUser(int id)
        {
            ADMIN ad = (ADMIN)Session["Admin"];
            if (ad == null)
            {
                return RedirectToAction("Index", "Home");
            }
            NGUOIDUNG nd = data.NGUOIDUNGs.SingleOrDefault(n => n.ID == id);
            ViewBag.Mand = nd.ID;
            if (nd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(nd);
        }

        [HttpPost, ActionName("DeleteUser")]
        public ActionResult DeleteUser(int id, FormCollection collection)
        {
            THONGKEWEB tk_web = data.THONGKEWEBs.SingleOrDefault(n => n.ID == 1);

WebDulich/WebDulich/Views/AdminManager/AcceptWrite.cshtml
@model WebDulich.Models.BAIVIET

@{
    ViewBag.Title = "Khám phá | Sửa Bài Viết";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section muc{
    Tin tức
}

@section muc1{
    Tin tức
}

@section chucnang{
    Sửa
}


<div class="content">

    @using (Html.BeginForm("AcceptWrite", "AdminManager", null, FormMethod.Post, new { enctype = "multipart/form-data", id = "formCreate" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label class="control-label col-md-3" name="id_loai" for="pwd">Loại tin:</label>
                <div class="col-md-5">
                    @Html.DropDownListFor(model => model.ID_LOAI, ViewBag.listCate as IEnumerable<SelectListItem>, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Người viết:</label>
                <div class="col-md-5">
                    <label>
                        @if (Model.ID_USER != null)
                        {
                            @Model.NGUOIDUNG.TEN
                        }
                        else
                        {
                            @Model.NGUOIDUNGFB.TEN
                        }
                    </label>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" name="tieude" for="pwd">Tiêu đề:</label>
                <div class="col-md-5">
                    @Html.EditorFor(model => model.TIEUDE, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TIEUDE, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" name="mota" for="pwd">Mô tả:</label>
                <div class="col-md-5">
                    @Html.EditorFor(model => model.MOTA, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MOTA, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Ảnh Bìa:</label>
                <div class="col-md-5">
                    <img src="@Model.ANHBIA" alt="hinh" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Ảnh bìa cần thay đổi:</label>
                <div class="col-md-5">
                    <input type="text" name="hinh" id="HinhAnh" value="@Model.ANHBIA" />
                    <input type="button" value="Chọn Ảnh ..." onclick="BrowseServer('');" />
                </div>
            </div>

            @*<div class="form-group">
                    <label class="control-label col-md-3" for="pwd">Ngày đăng:</label>
                    <div class="col-md-5">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            @Html.EditorFor(model => model.NGAYDANG, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NGAYDANG, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>*@

            <div class="form-group">
                <label class="control-label col-sm-3" for="pwd">Nội dung:</label>
                <div class="col-sm-7">
                    <textarea id="editor1" name="noidung" rows="3">
                        @Model.NOIDUNG
                    </textarea>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-3 col-md-10">
                    <input type="submit" value="Duyệt" class="btn btn-success" /> |
                    @Html.ActionLink("Trở về", "ListWrite")
                </div>
            </div>
        </div>
    }
</div>

WebDulich/WebDulich/Views/AdminManager/CreatePost.cshtml
@model WebDulich.Models.TINTUC

@{
    ViewBag.Title = "Khám phá | Thêm Tin Tức";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section muc{
    Tin tức
}

@section muc1{
    Tin tức
}

@section chucnang{
    Thêm
}

<div class="content">

    @using (Html.BeginForm("CreatePost", "AdminManager", null, FormMethod.Post, new { enctype = "multipart/form-data", id = "formCreate" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Loại tin:</label>
                <div class="col-md-5">
                    @Html.DropDownListFor(model => model.ID_LOAI, ViewBag.listCate as IEnumerable<SelectListItem>, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Tiêu đề:</label>
                <div class="col-md-5" >
                    @Html.EditorFor(model => model.TENTIN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TENTIN, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Mô tả:</label>
                <div class="col-md-5">
                    @Html.EditorFor(model => model.MOTA, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MOTA, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Hình ảnh:</label>
                <div class="col-md-5">
                    <input type="text" name="hinh" id="HinhAnh" />
                    <input type="button" value="Chọn Ảnh ..." onclick="BrowseServer('');" />
                </div>
            </div>

            @*<div class="form-group">
                <label class="control-label col-md-3" for="pwd">Ngày đăng:</label>
                <div class="col-md-5">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        @Html.EditorFor(model => model.NGAYDANG, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NGAYDANG, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>*@

            <div class="form-group">
                <label class="control-label col-sm-3" for="pwd">Nội dung:</label>
                <div class="col-sm-7">
                    <textarea id="editor1" name="noidung" rows="3">
                        
                    </textarea>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-3 col-md-10">
                    <input type="submit" value="Thêm" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

</div>

WebDulich/WebDulich/Views/AdminManager/DetailWrite.cshtml
@model WebDulich.Models.BAIVIET
@{
    ViewBag.Title = "Khám phá | Thông Tin Bài Viết";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section muc{
    Người dùng
}

@section muc1{
    Người dùng
}

@section chucnang{
    Danh sách
}

<div class="container">
    <div class="box-body">
        @using (Html.BeginForm("AcceptWrite", "AdminManager", null, FormMethod.Post, new { enctype = "multipart/form-data", id = "formCreate" }))
        {
            @Html.AntiForgeryToken()
            <div class="col-lg-10">
                <p><h4><b>- Tiêu đề:</b> @Model.TIEUDE</h4></p>
                @if (Model.ID_USER != null)
                {
                    <p><h4><b>- Người viết:</b> @Model.NGUOIDUNG.TEN</h4></p>
                }
                else
                {
                    <p><h4><b>- Người viết:</b> @Model.NGUOIDUNGFB.TEN</h4></p>
                }
                <p><h4><b>- Loại tin:</b> @Model.LOAITIN.TENLOAI</h4></p>
                <p><h4><b>- Mô tả:</b> @Model.MOTA</h4></p>
                <p><h4><b>- Ngày đăng:</b> @Model.NGAYDANG</h4></p>
                <p>
                    <h4><b>- Hình ảnh:</b></h4><img src="@Model.ANHBIA" alt="hinh" />
                </p>
                <p><h4><b>- Nội dung:</b> @Html.Raw(@Model.NOIDUNG)</h4></p>
            </div>

            <div class="form-group">
                <div class="col-md-offset-1 col-md-10">
                    @Html.ActionLink("Duyệt", "AcceptWrite", new { id = Model.ID }) |
                    @Html.ActionLink("Sửa", "EditWrite", new { id = Model.ID }) |
                    @Html.ActionLink("Quay lại", "ListWrite")
                </div>
            </div>

        }
    </div>
</div>

WebDulich/WebDulich/Views/AdminManager/EditUser.cshtml
@model WebDulich.Models.NGUOIDUNG

@{
    ViewBag.Title = "EditUser";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section muc{
    Tin tức
}

@section muc1{
    Tin tức
}

@section chucnang{
    Sửa
}


<div class="content">

    @using (Html.BeginForm("EditUser", "AdminManager", null, FormMethod.Post, new { enctype = "multipart/form-data", id = "formCreate" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Họ tên:</label>
                <div class="col-md-5">
                    @Html.EditorFor(model => model.TEN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TEN, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Tên đăng nhập:</label>
                <div class="col-md-5">
                    @Html.EditorFor(model => model.TENDN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TENDN, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Mật khẩu:</label>
                <div class="col-md-5">
                    @Html.EditorFor(model => model.PASS, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PASS, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Email:</label>
                <div class="col-md-5">
                    @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Số ĐT:</label>
                <div class="col-md-5">
                    @Html.EditorFor(model => model.SODT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SODT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-3 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-success" /> |
                    @Html.ActionLink("Trở về", "ListUser")
                </div>
            </div>
        </div>
    }
</div>

WebDulich/WebDulich/Views/AdminManager/EditWrite.cshtml
@model WebDulich.Models.BAIVIET

@{
    ViewBag.Title = "Khám phá | Sửa Bài Viết";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section muc{
    Tin tức
}

@section muc1{
    Tin tức
}

@section chucnang{
    Sửa
}


<div class="content">

    @using (Html.BeginForm("EditWrite", "AdminManager", null, FormMethod.Post, new { enctype = "multipart/form-data", id = "formCreate" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label class="control-label col-md-3" name="id_loai"for="pwd">Loại tin:</label>
                <div class="col-md-5">
                    @Html.DropDownListFor(model => model.ID_LOAI, ViewBag.listCate as IEnumerable<SelectListItem>, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Người viết:</label>
                <div class="col-md-5">
                    <label>
                        @if (Model.ID_USER != null)
                        {
                            @Model.NGUOIDUNG.TEN
                        }
                        else
                        {
                            @Model.NGUOIDUNGFB.TEN
                        }
                    </label>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" name="tieude" for="pwd">Tiêu đề:</label>
                <div class="col-md-5">
                    @Html.EditorFor(model => model.TIEUDE, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TIEUDE, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" name="mota" for="pwd">Mô tả:</label>
                <div class="col-md-5">
                    @Html.EditorFor(model => model.MOTA, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MOTA, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Ảnh Bìa:</label>
                <div class="col-md-5">
                    <img src="@Model.ANHBIA" alt="hinh" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3" for="pwd">Ảnh bìa cần thay đổi:</label>
                <div class="col-md-5">
                    <input type="text" name="hinh" id="HinhAnh" value="@Model.ANHBIA"/>
                    <input type="button" value="Chọn Ảnh ..." onclick="BrowseServer('');" />
                </div>
            </div>

            @*<div class="form-group">
                <label class="control-label col-md-3" for="pwd">Ngày đăng:</label>
                <div class="col-md-5">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        @Html.EditorFor(model => model.NGAYDANG, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NGAYDANG, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>*@

            <div class="form-group">
                <label class="control-label col-sm-3" for="pwd">Nội dung:</label>
                <div class="col-sm-7">
                    <textarea id="editor1" name="noidung" rows="3">
                        @Model.NOIDUNG
                    </textarea>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-3 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-success" /> |
                    @Html.ActionLink("Trở về", "ListWrite")
                </div>
            </div>
        </div>
    }
</div>

WebDulich/WebDulich/Views/AdminManager/ListWrite.cshtml
@using WebDulich.Models;
@using PagedList.Mvc;

@model PagedList.PagedList<WebDulich.Models.BAIVIET>

@{
    ViewBag.Title = "Khám phá | Danh sách Tin Tức";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section muc{
    Bài viết
}

@section muc1{
    Bài viết
}

@section chucnang{
    Danh sách
}

<div class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h2 class="box-title">Danh sách bài viết từ người dùng</h2>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    @using (Html.BeginForm("SearchWrite", "AdminManager", FormMethod.Get))
                    {
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="sTuKhoa" placeholder="Tìm kiếm...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="submit">Tìm kiếm</button>
                                    </span>
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    }
                    <br />
                    <table id="example1" class="table table-bordered table-striped">
                        <tr>
                            <th>
                                STT
                            </th>
                            <th>
                                Tiêu đề
                            </th>
                            <th>
                                Loại tin
                            </th>
                            <th>
                                Người Viết
                            </th>
                            <th>
                                Ngày đăng
                            </th>
                            <th>
                                Hình ảnh
                            </th>
                            <th></th>
                        </tr>

                        @{
                            var stt = 0;
                        }
                        @foreach (var item in Model)
                        {
                            stt += 1;
                            <tr>
                                <td>
                                    @stt
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TIEUDE)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LOAITIN.TENLOAI)
                                </td>
                                <td>
                                    @if (item.ID_USER != null)
                                    {
                                        @Html.DisplayFor(modelItem => item.NGUOIDUNG.TENDN)
                                    }
                                    else
                                    {
                                        @Html.DisplayFor(modelItem => item.NGUOIDUNGFB.TENDN)
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NGAYDANG)
                                </td>
                                <td>
                                    <img src="@item.ANHBIA" width="95" title="hình ảnh" />
                                </td>
                                <td>
                                    @Html.ActionLink("Sửa", "EditWrite", new { id = item.ID }) |
                                    @Html.ActionLink("Chi tiết", "DetailWrite", new { id = item.ID }) |
                                    @Html.ActionLink("Xóa", "DeleteWrite", new { id = item.ID })
                                </td>
                            </tr>
                        }

                    </table>
                    <br />
                    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
                    <div class="MenuTrang">
                        @Html.PagedListPager(Model, page => Url.Action("ListWrite", new { page = page }))
                    </div>
                    <style>
                        .MenuTrang li {
                            display: inline;
                        }
                    </style>
                </div>
                <!-- /.box-body -->

            </div>

        </div>
    </div>
</div>