WebDulich/WebDulich/Controllers/LienheController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDulich.Models;

namespace WebDulich.Controllers
{
    public class LienheController : Controller
    {
        DULICHEntities1 data = new DULICHEntities1();
        // GET: Lienhe
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SaveMessage([Bind(Include = "HOTEN, EMAIL, SODT, NOIDUNG")] TINNHAN tn, FormCollection collection)
        {
            var noidung = collection["Noidung"];
            try
            {
                if (ModelState.IsValid)
                {
                    tn.NOIDUNG = noidung;
                    data.TINNHANs.Add(tn);
                    data.SaveChanges();
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Có lỗi xảy ra");
            }
            return RedirectToAction("Index");
        }
    }
}

WebDulich/WebDulich/Controllers/TintucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDulich.Models;
using System.IO;
using System.Data.Entity.Infrastructure;
using PagedList;
using PagedList.Mvc;

namespace WebDulich.Controllers
{
    public class TintucController : Controller
    {
        DULICHEntities1 data = new DULICHEntities1();

        public ActionResult Index(int ?page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 20;
            // return View(data.TINTUCs.ToList());
            return View(data.TINTUCs.ToList().OrderBy(n => n.ID).ToPagedList(pageNumber, pageSize));
        }

    }
}

WebDulich/WebDulich/Views/Shared/_LayoutAdmin.cshtml
@using WebDulich.Models;
@{ 
    ADMIN ad = (ADMIN)Session["Admin"];
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Content/dist/css/skins/_all-skins.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Content/plugins/iCheck/flat/blue.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="~/Content/plugins/morris/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="~/Content/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="~/Content/plugins/datepicker/datepicker3.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/Content/plugins/daterangepicker/daterangepicker.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="~/Content/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index","Home")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>K</b>P</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Khám</b> Phá</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="~/Assets/images/mienbac.jpg" class="user-image" alt="User Image">
                                <span class="hidden-xs">@ad.HOTEN</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="~/Assets/images/mienbac.jpg" class="img-circle" alt="User Image">
                                    <p>
                                       @ad.HOTEN
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-right">
                                        <a href="/UserAccount/Dangxuat" class="btn btn-default btn-flat">Đăng Xuất</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/Assets/images/mienbac.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>@ad.HOTEN</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header">Bảng điều khiển</li>
                    <li class="active treeview">
                        <a href="@Url.Action("Index", "AdminManager")">
                            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                        </a>
                    </li>

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-user"></i> <span> Người Dùng</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("ListUser", "AdminManager")"> Danh sách</a></li>
                        </ul>
                    </li> 

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-facebook"></i> <span> Người Dùng Facebook</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("ListUserFb", "AdminManager")"> Danh sách</a></li>
                        </ul>
                    </li> 
                    
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-newspaper-o"></i> <span>Tin tức</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("ListPost", "AdminManager")"> Danh sách</a></li>
                            <li><a href="@Url.Action("CreatePost", "AdminManager")"> Thêm</a></li>
                        </ul>
                    </li> 

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-edit"></i> <span> Bài Viết</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("ListWrite", "AdminManager")"> Danh sách</a></li>
                        </ul>
                    </li> 

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-envelope"></i> <span> Lời Nhắn</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("ListMessage", "AdminManager")"> Danh sách</a></li>
                        </ul>
                    </li> 


                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @RenderSection("muc", true)
                    <small>@RenderSection("chucnang", true)</small>
                </h1>

                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li class="active">@RenderSection("muc1", true)</li>
                </ol>
            </section>

            <hr />

            <!-- main content -->
            @RenderBody()
            <!-- /main content -->

        </div>

        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="container">
                <p class="text-muted">© 2016 Design Kham Pha - by  <a href="http://hutech.edu.vn">Việt Anh & Phú Lộc</a></p>
            </div>
        </footer>
  
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 2.2.3 -->
    <script src="~/Content/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
  $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.6 -->
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="~/Content/plugins/morris/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="~/Content/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="~/Content/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/Content/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/Content/plugins/knob/jquery.knob.js"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
    <script src="~/Content/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="~/Content/plugins/datepicker/bootstrap-datepicker.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="~/Content/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Slimscroll -->
    <script src="~/Content/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- iCheck 1.0.1 -->
    <script src="../../plugins/iCheck/icheck.min.js"></script>
    <!-- FastClick -->
    <script src="~/Content/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/app.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Content/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/dist/js/demo.js"></script>


    <script src="~/Content/ckeditor/ckeditor.js"></script>
    <script src="~/Content/ckfinder/ckfinder.js"></script>
    <script type="text/javascript">
        CKEDITOR.replace('editor1',
        {
                filebrowserBrowseUrl : '/Content/ckfinder/ckfinder.html',
                filebrowserImageUrl : '/Content/ckfinder/ckfinder.html?type=Images',
                filebrowserFlashUrl : '/Content/ckfinder/ckfinder.html?type=Flash',
                filebrowserUploadUrl:
 	           '/Content/ckfinder/core/connector/aspx/connector.aspx?command=QuickUpload&type=Files&',
                filebrowserImageUploadUrl:
	           '/Content/ckfinder/core/connector/aspx/connector.aspx?command=QuickUpload&type=Images&',
                filebrowserFlashUploadUrl: '/Content/ckfinder/core/connector/aspx/connector.aspx?command=QuickUpload&type=Flash'
        });

    </script>

    <script type="text/javascript">
        var id = null;
        function BrowseServer(num) {
            id = num;
            var finder = new CKFinder();
            //finder.basePath = '../';
            finder.selectActionFunction = SetFileField;
            finder.popup();
        }
        function SetFileField(fileUrl) {
            document.getElementById('HinhAnh' + id).value = fileUrl;
        }
    </script>
</body>
</html>

WebDulich/WebDulich/Views/Shared/_LayoutLogin.cshtml
@using WebDulich.Models;
@{
    Layout = null;
    NGUOIDUNG user = (NGUOIDUNG)Session["taikhoan"];
}

<!DOCTYPE html>
<html lang="vi">

<head>
    <!-- 1.0 meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <!-- 2.0 title -->
    <title>@ViewBag.Title</title>
    <!-- 3.0 CSS IMPORT -->
    <!-- CSS IMPORT FOR PLUGIN -->
    <link href="~/Assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Assets/js/wow/css/libs/animate.css" rel="stylesheet" />
    <link href="~/Assets/js/wordsrotator/jquery.wordrotator.min.css" rel="stylesheet" />
    <link href="~/Assets/css/Bootstrap-social.css" rel="stylesheet" />
    <!-- CSS IMPORT FOR FONT -->
    <link href='https://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href="~/Assets/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!-- CSS IMPORT FOR MAIN STYLE -->
    <link href="~/Assets/css/stylehome.css" rel="stylesheet" />
    <link href="~/Assets/css/login.css" rel="stylesheet" />

    <style>
        .open > .dropdown-menu-login {
            display: block;
        }

        .dropdown-menu-login {
            position: absolute;
            top: 100%;
            left: 0;
            z-index: 1000;
            display: none;
            float: left;
            min-width: 160px;
            padding: 5px 0;
            margin: 2px 0 0;
            font-size: 14px;
            text-align: left;
            list-style: none;
            -webkit-background-clip: padding-box;
            background-clip: padding-box;
            border: 1px solid #ccc;
            border: 1px solid rgba(0,0,0,.15);
            border-radius: 4px;
            -webkit-box-shadow: 0 6px 12px rgba(0,0,0,.175);
            box-shadow: 0 6px 12px rgba(0,0,0,.175);
        }

        ol ol, ol ul, ul ol, ul ul {
            margin-bottom: 0;
        }

        ol, ul {
            list-style: none;
            margin: 0px;
            padding: 0px;
        }

        ul {
            padding-left: 0;
        }

        ol, ul {
            margin-top: 0;
            margin-bottom: 10px;
        }

        * {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }

        ul li {
            list-style: none;
        }

        .text-center {
            text-align: center;
        }

        html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, dl, dt, dd, ol, nav ul, nav li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {
            font-size: 100%;
            font: inherit;
        }

        body {
            font-family: 'Open Sans', sans-serif;
        }
    </style>

</head>
<body>
    <!-- 6.0 wrapper -->
    <div class="wrapper" id="wrapper-large">
        <div class="container-fluid">
            <!-- 6.2 HOME & RETURN BUTTONS -->
            <ul class="return-btn center-block text-center center-icon">
                <li>
                    <a href="@Url.Action("Index", "Home")" class="wow slideInLeft">Trang Chủ <span class="icons-container"><span class="home-icon"></span></span></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle wow slideInRight" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-fw fa-map-marker"></span>Địa Danh<span class="caret"></span></a>
                    <ul class="dropdown-menu-login dropdowncostume-login text-center">
                        <li><a href="@Url.Action("Mienbac", "Diadanh")"><span class="fa fa-fw fa-map-marker"></span>Miền Bắc</a></li>
                        <li><a href="@Url.Action("Mientrung", "Diadanh")"><span class="fa fa-fw fa-map-marker"></span>Miền Trung</a></li>
                        <li><a href="@Url.Action("Miennam", "Diadanh")"><span class="fa fa-fw fa-map-marker"></span>Miền Nam</a></li>
                        <li><a href="@Url.Action("Mientay", "Diadanh")"><span class="fa fa-fw fa-map-marker"></span>Miền Tây</a></li>
                        <li><a href="@Url.Action("Taynguyen", "Diadanh")"><span class="fa fa-fw fa-map-marker"></span>Tây Nguyên</a></li>
                        <li><a href="@Url.Action("Biendao", "Diadanh")"><span class="fa fa-fw fa-map-marker"></span>Biền Đảo</a></li>
                    </ul>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Tintuc")" class="wow slideInLeft"><span class="fa fa-fw fa-newspaper-o"></span>Tin Tức </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Lienhe")" class="wow slideInRight"><span class="fa fa-fw fa-book"></span>Liên Hệ </a>
                </li>
                @if (user != null)
                {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle wow slideInLeft" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-fw fa-user"></span><small>@user.TEN </small><span class="caret"></span></a>
                        <ul class="dropdown-menu-login dropdowncostume-login text-center">
                            <li> <a href="@Url.Action("Thongtin", "UserAccount")"><span class="fa fa-fw fa-user"></span>Thông Tin</a></li>
                            <li> <a href="@Url.Action("Vietbai", "UserAccount")"><span class="fa fa-fw fa-edit"></span>Viết Bài</a></li>
                            <li> <a href="@Url.Action("Doimatkhau", "UserAccount")"><span class="fa fa-fw fa-refresh"></span>Đổi Mật Khẩu</a></li>
                            <li><a href="@Url.Action("Dangxuat", "UserAccount")"><span class="fa fa-fw fa-sign-out"></span>Đăng Xuất</a></li>
                        </ul>
                    </li>
                }
                else
                {
                    <li>
                        <a href="@Url.Action("Dangnhap", "UserAccount")" class="wow slideInLeft"><span class="fa fa-fw fa-sign-in"></span>Đăng Nhập</a>
                    </li>
                }

            </ul>
            <!-- end HOME & RETURN BUTTONS -->

            <div class="row">
                <div class="col-sm-12 text-center">
                    <!-- 6.1 SPIRIT BUBBLES CANVAS -->
                    <canvas class="spirit-bubbles" id="canvas"></canvas>
                    <!-- end SPIRIT BUBBLES CANVAS -->

                    <div>@RenderBody()</div>

                </div>
            </div>
        </div>
    </div>
    <!-- end wrapper -->
    <!-- 7.0 javascript import -->
    <!-- jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- bootstrap -->
    <script src="~/Assets/bootstrap/js/bootstrap.min.js"></script>
    <!-- wow -->
    <script src="~/Assets/js/wow/dist/wow.min.js"></script>
    <!-- wordsrotator -->
    <script src="~/Assets/js/wordsrotator/jquery.wordrotator.min.js"></script>
    <!-- main js -->
    <script src="~/Assets/js/main.js"></script>
    <script>
      function initMap() {
        var mapDiv = document.getElementById('map');
        var map = new google.maps.Map(mapDiv, {
            center: {lat: 15.5, lng: 108.3},
            zoom: 7
        });
      }
    </script>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAqo8MnAQmieH3VKYSY8zN_wuE2NA7nPd8&callback=initMap">
    </script>

</body>

</html>

WebDulich/WebDulich/Views/Shared/_LayoutVungmien.cshtml
@using WebDulich.Models;
@{ 
    NGUOIDUNG nd = (NGUOIDUNG)Session["TaiKhoan"];
}
@{
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
            @RenderSection("script", true);


    <div id="about">
        <div class="container">
            <div id="body">



                <section id="contentt" class="col-xs-12 col-lg-8">
                    @RenderBody()
                    @if (nd != null)
                    {
                        <label class="control-label col-sm-12 col-md-12 text-left" style="color:red"><i>Nếu bạn có một bài viết gì hay về review các điểm du lịch vui lòng viết bài <a href="@Url.Action("Vietbai", "UserAccount")">ở đây</a> để giới thiệu đến mọi người!</i></label>
                    }
                    else
                    {
                        <label class="control-label col-sm-12 col-md-12 text-left" style="color:red"><i>Nếu bạn có một bài viết gì hay về review các điểm du lịch vui lòng viết bài để giới thiệu đến mọi người. Hãy </i><a href="@Url.Action("Dangnhap", "UserAccount")">đăng nhập</a><i> để viết bài!</i></label>
                    }


                </section>

                <section id="contentt" class="col-xs-12 col-lg-4 text-center">
                    <h2 class="title-search text-center"> Vùng miền </h2>
                    <a href="@Url.Action("Mienbac", "Diadanh")"> <h4>Du lịch Miền Bắc</h4></a>
                    <hr />
                    <a href="@Url.Action("Mientrung", "Diadanh")"> <h4>Du lịch Miền Trung</h4></a>
                    <hr />
                    <a href="@Url.Action("Miennam", "Diadanh")"> <h4>Du lịch Miền Nam</h4></a>
                    <hr />
                    <a href="@Url.Action("Mientay", "Diadanh")"> <h4>Du lịch Miền Tây</h4></a>
                    <hr />
                    <a href="@Url.Action("Taynguyen", "Diadanh")"> <h4>Du lịch Tây Nguyên</h4></a>
                    <hr />
                    <a href="@Url.Action("Biendao", "Diadanh")"> <h4>Du lịch Biển Đảo</h4></a>
                    <hr />
                    <div class="fb-page" data-href="https://www.facebook.com/kpdulichvn/" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/asstorevn/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/kpdulichvn/">Khám Phá Du Lịch Việt Nam</a></blockquote></div>
                </section>

            </div>
        </div>
    </div>
</body>
</html>